var quotes = [
'When all is one and one is all, that\'s what it is... To be a rock and not to roll. Led Zeppelin',
'I\'m into rock \'n roll because rock \'n roll, to me, means freedom. Ozzy Osbourne',
'I wanted to have the adoration of John Lennon but have the anonymity of Ringo Starr. I didn\'t want to be a frontman. I just wanted to be back there and still be a rock and roll star at the same time. Kurt Cobain',
'Drive away and try to keep smiling. Get a little rock and roll on the radio and go toward life with all the courage you can find and all the belief you can muster. Be true, be brave, stand. Stephen King, It: A Novel',
'Elvis may be the King of Rock and Roll, but I am the Queen. Little Richard',
'Rock and roll music, if you like it, if you feel it, you can\'t help but move to it. That\'s what happens to me. I can\'t help it. Elvis Presley',
'A lot of people seem to think I started this business. But rock \'n\' roll was here a long time before I came along. Nobody can sing that kind of music like colored people. Let\'s face it: I can\'t sing like Fats Domino can. I know that. Elvis Presley',
'We\'re more popular than Jesus now; I don\'t know which will go first, rock \'n\' roll or Christianity. John Lennon',
'The great thing about rock and roll is that someone like me can be a star. Elton John',
'Music is my religion. Jimi Hendrix',
'Big wheels keep on turning... Lynyrd Skynyrd',
'Singing, I love rock and roll... Arrows',
'Smoke on the water, a fire in the sky. Deep Purple',
'Life is a mystery... Madonna',
'Music is like a dream. One that I cannot hear. Ludwig van Beethoven',
'I think music in itself is healing. It’s an explosive expression of humanity. It’s something we are all touched by. No matter what culture we’re from, everyone loves music. Billy Joel',
'One good thing about music, when it hits you, you feel no pain. Bob Marley',
'After silence, that which comes nearest to expressing the inexpressible is music.” ― Aldous Huxley',
'Music touches us emotionally, where words alone can’t. Johnny Depp',
'I like beautiful melodies telling me terrible things. Tom Waits',
'If being an egomaniac means I believe in what I do and in my art or music, then in that respect you can call me that… I believe in what I do, and I’ll say it. John Lennon',
'Information is not knowledge. Knowledge is not wisdom. Wisdom is not truth. Truth is not beauty. Beauty is not love. Love is not music. Music is THE BEST. Frank Zappa',
'I might be moving to Montana soon just to raise me up a crop of dental floss. Frank Zappa',
'Without music to decorate it, time is just a bunch of boring production deadlines or dates by which bills must be paid. Frank Zappa',
'The world is a vampire. Billy Corgan',
'Music is the strongest form of magic. Marilyn Manson',
'Music is everybody’s business. It’s only the publishers who think people own it. John Lennon',
'People ask me how I make music. I tell them I just step into it. It’s like stepping into a river and joining the flow. Every moment in the river has its song. Michael Jackson',
'I’m just a musical prostitute, my dear. Freddie Mercury',
'To live is to be musical, starting with the blood dancing in your veins. Everything living has a rhythm. Do you feel your music? Michael Jackson',
'Love is friendship set to music. Jackson Pollock',
'All that we are is the result of what we have thought. Buddha',
'If you judge people, you have no time to love them. Mother Teresa',
'The most courageous act is still to think for yourself. Aloud. Coco Chanel',
'The greatest wealth is to live content with little. Plato',
'The future belongs to those who prepare for it today. Malcolm X',
'I have no special talent. I am only passionately curious. Albert Einstein',
'The successful warrior is the average man, with laser-like focus. Bruce Lee',
'Those who dare to fail miserably can achieve greatly. John F. Kennedy',
'A great man is always willing to be little. Ralph Waldo Emerson',
'The root of suffering is attachment. Buddha',
'Wisely, and slow. They stumble that run fast. William Shakespeare',
'Keep calm and carry on. Winston Churchill',
'To be, or not to be, that is the question. William Shakespeare',
'That’s one small step for a man, one giant leap for mankind. Neil Armstrong',
'Early to bed and early to rise makes a man healthy, wealthy, and wise. Benjamin Franklin',
'Ask not what your country can do for you, but what you can do for your country. John F. Kennedy',
'Family is the most important thing in the world. Diana (Princess of Wales)',
'All I was doing was trying to get home from work. Rosa Parks',
'I came, I saw, I conquered. Julius Caesar',
'I think, therefore I am. René Descartes',
'Whenever you find yourself on the side of the majority, it is time to pause and reflect. Mark Twain',
'Be yourself; everyone else is already taken. Oscar Wilde',
'The journey of a thousand miles begins with one step. Lao Tzu',
'I’ve failed over and over and over again in my life and that is why I succeed. Michael Jordan',
'It does not matter how slowly you go so long as you do not stop. Confucius',
'It’s not whether you get knocked down, it’s whether you get up. Vince Lombardi',
'Go confidently in the direction of your dreams. Live the life you have imagined. Henry David Thoreau',
'You miss 100 percent of the shots you never take. Wayne Gretzky',
'Nonviolence is a weapon of the strong. Mahatma Gandhi',
'Peace begins with a smile. Mother Teresa',
'Stay hungry, stay foolish. Steve Jobs',
'Good artists copy, great artists steal. Pablo Picasso',
'Big Brother is watching you. George Orwell',
'Education is the most powerful weapon which you can use to change the world. Nelson Mandela',
'The only thing that interferes with my learning is my education. Albert Einstein',
'Genius is one percent inspiration, ninety-nine percent perspiration. Thomas A. Edison',
'If you think you can do a thing or think you can’t do a thing, you’re right. Henry Ford',
'Better to die standing than to live on your knees. Ernesto “Che” Guevara',
'It always seems impossible until it’s done. Nelson Mandela',
'Try not to become a man of success but rather to become a man of value. Albert Einstein',
'Insanity: doing the same thing over and over again and expecting different results. Albert Einstein',
'Our life is frittered away by detail… simplify, simplify. Henry David Thoreau',
'The weak can never forgive. Forgiveness is the attribute of the strong. Mahatma Gandhi',
'Well done is better than well said. Benjamin Franklin',
'The unexamined life is not worth living. Socrates',
'Turn your wounds into wisdom. Oprah Winfrey',
'I don’t think of all the misery but of the beauty that still remains. Anne Frank',
'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. Bruce Lee',
'A man who stands for nothing will fall for anything. Malcolm X',
'Love all, trust a few, do wrong to none. William Shakespeare (wikipedia.org)',
'Do what you can, with what you have, where you are. Theodore Roosevelt',
'Little by little, one travels far. J.R.R. Tolkien',
'Be kind whenever possible. It is always possible. 14th Dalai Lama',
'I have a dream that one day little black boys and girls will be holding hands with little white boys and girls. Martin Luther King Jr',
'God helps those that help themselves. Benjamin Franklin',
'By failing to prepare, you are preparing to fail. Benjamin Franklin',
'No. Rosa Parks',
'Fear is stupid. So are regrets. Marilyn Monroe',
'Do something worth remembering. Elvis Presley',
'Whatever you are, be a good one. Abraham Lincoln',
'Better to build a bridge than a wall. Elton John',
'Be proud of who you are. Eminem',
'Genius is eternal patience. Michelangelo',
'Not all those who wander are lost. J.R.R. Tolkien',
'It is not in the stars to hold our destiny but in ourselves. William Shakespeare',
'I am the greatest, I said that even before I knew I was. Muhammad Ali',
'I would like to die on Mars. Just not on impact. Elon Musk',
'Winners never quit, and quitters never win. Vince Lombardi',
'Simplicity is the ultimate sophistication. Leonardo da Vinci',
'Nobody can hurt me without my permission. Mahatma Gandhi',
'It’s fun to do the impossible. Walt Disney',
'Have no fear of perfection, you’ll never reach it. Salvador Dali',
'We need fantasy to survive reality. Lady Gaga',
'The future starts today, not tomorrow. Pope John Paul II',
'The best way to predict your future is to create it. Abraham Lincoln',
'If not us, who? If not now, when? John F. Kennedy',
'Stumbling is not falling. Malcolm X',
'The future belongs to those who believe in the beauty of their dreams. Eleanor Roosevelt',
'We are all of us stars, and we deserve to twinkle. Marilyn Monroe',
'Those who say it can’t be done are usually interrupted by others doing it. James Baldwin',
'We don’t want to tell our dreams. We want to show them. Cristiano Ronaldo',
'Power is not given to you. You have to take it. Beyoncé',
'You laugh at me because I’m different I laugh at you because you’re all the same. Lady Gaga',
'I have learned over the years that when one’s mind is made up, this diminishes fear; knowing what must be done does away with fear. Rosa Parks',
'If I have seen further than others, it is by standing upon the shoulders of giants. Isaac Newton',
'Learn to value yourself, which means: to fight for your happiness. Ayn Rand',
'You’ll never find a rainbow if you’re looking down. Charlie Chaplin',
'That which does not kill us makes us stronger. Friedrich Nietzsche',
'Wise men talk because they have something to say; fools, because they have to say something. Plato',
'Once you’ve accepted your flaws, no one can use them against you. George R.R. Martin',
'If you can’t convince them, confuse them. Harry S. Truman',
'I don’t care that they stole my idea… I care that they don’t have any of their own. Nikola Tesla',
'A fool thinks himself to be wise, but a wise man knows himself to be a fool. William Shakespeare',
'If you don’t like something, change it. If you can’t change it, change your attitude. Maya Angelou',
'Too often we enjoy the comfort of opinion without the discomfort of thought. John F. Kennedy',
'There is nothing so useless as doing efficiently that which should not be done at all. Peter Drucker',
'Doubt is not a pleasant condition, but certainty is absurd. Voltaire',
'We must use time as a tool, not as a couch. John F. Kennedy',
'Someone’s sitting in the shade today because someone planted a tree a long time ago. Warren Buffett',
'Change will not come if we wait for some other person or some other time. We are the ones we’ve been waiting for. We are the change that we seek. Barack Obama',
  /*test quotes
  'The trickster\'s function is to break taboos, create mischief, stir things up. In the end, the trickster gives people what they really want, some sort of freedom. - Tom Robbins',
  'Disbelief in magic can force a poor soul into believing in government and business. - Tom Robbins',
  'The trouble with the fast lane is that all the movement is horizontal. And I like to go vertical sometimes. - Tom Robbins',
  'Our world isn\'t made of earth, air and water or even molecules and atoms; our world is made of language. - Tom Robbins',
  'I\'m not infatuated with frivolousness. We\'re just good friends. - Tom Robbins',
  'In fiction, when you paint yourself into a corner, you can write a pair of suction cups onto the bottoms of your shoes and walk up the wall and out the skylight and see the sun breaking through the clouds. In nonfiction, you don\'t have that luxury. - Tom Robbins',
  */
]
function newQuote() {
var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}